-- TasteNet PostgreSQL schema aligned with DeliverySystem.bacpac model.xml
-- and the ASP.NET SQL queries.
-- Run on an empty PostgreSQL 15+ / Supabase database as a migration owner.
-- Application access must use a separate, least-privileged database role.
-- Names use snake_case; see database/README.md for the MSSQL mapping.

BEGIN;
CREATE SCHEMA IF NOT EXISTS tastenet;
SET LOCAL search_path TO tastenet, public;

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(80) NOT NULL,
    email varchar(320) NOT NULL,
    password_hash text,
    google_subject text,
    role varchar(20) NOT NULL DEFAULT 'customer'
        CHECK (role IN ('customer', 'admin', 'superadmin', 'rider')),
    full_name varchar(200) NOT NULL,
    phone varchar(40),
    gender varchar(40),
    address text,
    is_active boolean NOT NULL DEFAULT true,
    profile_picture text,
    profile_photo text,
    rider_status varchar(30) NOT NULL DEFAULT 'offline',
    assigned_orders integer NOT NULL DEFAULT 0 CHECK (assigned_orders >= 0),
    completed_orders integer NOT NULL DEFAULT 0 CHECK (completed_orders >= 0),
    ratings numeric(3,2) NOT NULL DEFAULT 0 CHECK (ratings BETWEEN 0 AND 5),
    vehicle varchar(100),
    vehicle_model varchar(100),
    vehicle_year varchar(20),
    license_plate varchar(40),
    vehicle_color varchar(40),
    license_number varchar(100),
    nbi_number varchar(100),
    orcr_number varchar(100),
    insurance_policy varchar(150),
    insurance_date date,
    driver_license_photo text,
    orcr_photo text,
    insurance_photo text,
    nbi_clearance_photo text,
    date_joined timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_auth_method CHECK (password_hash IS NOT NULL OR google_subject IS NOT NULL)
);
CREATE UNIQUE INDEX IF NOT EXISTS users_username_ci_key ON users (lower(username));
CREATE UNIQUE INDEX IF NOT EXISTS users_email_ci_key ON users (lower(email));
CREATE UNIQUE INDEX IF NOT EXISTS users_google_subject_key ON users (google_subject) WHERE google_subject IS NOT NULL;
CREATE INDEX IF NOT EXISTS users_role_active_idx ON users (role, is_active);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash char(64) NOT NULL UNIQUE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS auth_sessions_user_id_idx ON auth_sessions (user_id);
CREATE INDEX IF NOT EXISTS auth_sessions_expires_at_idx ON auth_sessions (expires_at);

CREATE TABLE IF NOT EXISTS email_otps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(320) NOT NULL,
    otp_hash text NOT NULL,
    is_verified boolean NOT NULL DEFAULT false,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS email_otps_email_expires_idx ON email_otps (lower(email), expires_at DESC);

CREATE TABLE IF NOT EXISTS menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    food_name varchar(200) NOT NULL,
    food_type varchar(100) NOT NULL,
    description text,
    price numeric(12,2) NOT NULL CHECK (price >= 0),
    image_path text,
    status varchar(30) NOT NULL DEFAULT 'active',
    ratings numeric(3,2) NOT NULL DEFAULT 0 CHECK (ratings BETWEEN 0 AND 5),
    rating_count integer NOT NULL DEFAULT 0 CHECK (rating_count >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS menu_status_food_type_idx ON menu (status, food_type);

CREATE TABLE IF NOT EXISTS inventory_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name varchar(120) NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS inventory (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code varchar(80) NOT NULL UNIQUE,
    item_name varchar(200) NOT NULL,
    description text,
    category_id bigint REFERENCES inventory_categories(id) ON DELETE SET NULL,
    current_stock numeric(14,3) NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    minimum_stock numeric(14,3) NOT NULL DEFAULT 0 CHECK (minimum_stock >= 0),
    reorder_level numeric(14,3) NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
    is_available boolean NOT NULL DEFAULT true,
    unit_cost numeric(12,2) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
    unit_price numeric(12,2) NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
    unit_of_measure varchar(40) NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inventory_category_active_idx ON inventory (category_id, is_active);

CREATE TABLE IF NOT EXISTS inventory_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_id bigint NOT NULL REFERENCES inventory(id) ON DELETE RESTRICT,
    transaction_type varchar(40) NOT NULL,
    quantity numeric(14,3) NOT NULL,
    previous_stock numeric(14,3) NOT NULL,
    new_stock numeric(14,3) NOT NULL CHECK (new_stock >= 0),
    notes text,
    performed_by bigint REFERENCES users(id) ON DELETE SET NULL,
    transaction_date timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inventory_transactions_item_date_idx ON inventory_transactions (inventory_id, transaction_date DESC);

CREATE TABLE IF NOT EXISTS menu_recipe_ingredients (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id bigint NOT NULL REFERENCES menu(id) ON DELETE CASCADE,
    inventory_id bigint NOT NULL REFERENCES inventory(id) ON DELETE RESTRICT,
    quantity_required numeric(14,3) NOT NULL CHECK (quantity_required > 0),
    UNIQUE (menu_id, inventory_id)
);

CREATE TABLE IF NOT EXISTS delivery_fees (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    barangay_name varchar(120) NOT NULL UNIQUE,
    fee numeric(12,2) NOT NULL CHECK (fee >= 0)
);

CREATE TABLE IF NOT EXISTS payment_methods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_name varchar(120) NOT NULL UNIQUE,
    is_enabled boolean NOT NULL DEFAULT true,
    display_order integer NOT NULL DEFAULT 0,
    account_details text,
    instructions text,
    status varchar(20) NOT NULL DEFAULT 'Active',
    qr_photo text,
    created_at timestamptz NOT NULL DEFAULT now(),
    modified_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number varchar(80) NOT NULL UNIQUE,
    order_number varchar(80) NOT NULL UNIQUE,
    order_type varchar(40) NOT NULL,
    delivery_address text,
    status varchar(40) NOT NULL DEFAULT 'Open',
    priority varchar(30) NOT NULL DEFAULT 'Normal',
    total_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
    payment_method varchar(120),
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    rider_id bigint REFERENCES users(id) ON DELETE SET NULL,
    started_at timestamptz,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tickets_status_created_idx ON tickets (status, created_at DESC);
CREATE INDEX IF NOT EXISTS tickets_customer_created_idx ON tickets (created_by, created_at DESC);
CREATE INDEX IF NOT EXISTS tickets_rider_status_idx ON tickets (rider_id, status);

CREATE TABLE IF NOT EXISTS ticket_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    menu_id bigint REFERENCES menu(id) ON DELETE SET NULL,
    food_name varchar(200) NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0),
    sub_total numeric(12,2) NOT NULL CHECK (sub_total >= 0),
    special_instructions text,
    status varchar(30) NOT NULL DEFAULT 'Pending'
);
CREATE INDEX IF NOT EXISTS ticket_items_ticket_idx ON ticket_items (ticket_id);

CREATE TABLE IF NOT EXISTS proofs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id bigint NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
    proof_of_delivery text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS proofs_ticket_created_idx ON proofs (ticket_id, created_at DESC);

CREATE TABLE IF NOT EXISTS quotas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quota_type varchar(30) NOT NULL UNIQUE,
    target_amount numeric(14,2) NOT NULL CHECK (target_amount >= 0),
    start_date date NOT NULL,
    end_date date NOT NULL,
    CHECK (end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS rider_doc_approvals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    doc_column varchar(50) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'pending',
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_id, doc_column)
);

COMMIT;

-- Additional tables and columns verified against DeliverySystem.bacpac model.xml.
-- Kept additive so this file upgrades the first foundation schema as well.
BEGIN;
SET LOCAL search_path TO tastenet, public;

CREATE TABLE IF NOT EXISTS suppliers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code varchar(50) NOT NULL UNIQUE,
    supplier_name varchar(100) NOT NULL,
    contact_person varchar(100),
    email varchar(100),
    phone varchar(20),
    address varchar(255),
    tax_id varchar(50),
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE inventory ADD COLUMN IF NOT EXISTS supplier_id bigint REFERENCES suppliers(id) ON DELETE SET NULL;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS maximum_stock numeric(12,2);
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS is_perishable boolean DEFAULT false;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS expiry_date date;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS last_stock_take date;
ALTER TABLE inventory_categories ADD COLUMN IF NOT EXISTS description varchar(255);
ALTER TABLE inventory_categories ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE inventory_transactions ADD COLUMN IF NOT EXISTS reference_number varchar(100);
ALTER TABLE delivery_fees ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE delivery_fees ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
ALTER TABLE proofs ADD COLUMN IF NOT EXISTS proof_of_payment text;
ALTER TABLE proofs ALTER COLUMN proof_of_delivery DROP NOT NULL;
ALTER TABLE quotas ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE quotas ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();
ALTER TABLE menu ALTER COLUMN food_type DROP NOT NULL;
ALTER TABLE menu ALTER COLUMN ratings DROP NOT NULL;
ALTER TABLE ticket_items ALTER COLUMN quantity TYPE numeric(10,2);

CREATE TABLE IF NOT EXISTS admin_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(200) NOT NULL UNIQUE,
    username varchar(100) NOT NULL UNIQUE,
    password_hash text NOT NULL,
    full_name varchar(200),
    role varchar(50),
    is_active boolean DEFAULT true,
    is_two_factor_enabled boolean DEFAULT false,
    two_factor_secret_key text,
    last_login_date timestamptz,
    last_login_ip varchar(50),
    created_at timestamptz DEFAULT now(),
    modified_at timestamptz DEFAULT now(),
    created_by varchar(100)
);

CREATE TABLE IF NOT EXISTS application_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key varchar(100) NOT NULL UNIQUE,
    setting_value text,
    setting_data_type varchar(20),
    setting_category varchar(50),
    is_encrypted boolean DEFAULT false,
    created_at timestamptz DEFAULT now(),
    modified_at timestamptz DEFAULT now(),
    modified_by varchar(100)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type varchar(50),
    table_name varchar(100),
    record_id varchar(100),
    old_value text,
    new_value text,
    performed_by varchar(100),
    performed_date timestamptz,
    ip_address varchar(50)
);

CREATE TABLE IF NOT EXISTS order_status_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id varchar(50),
    old_status varchar(20),
    new_status varchar(20),
    changed_by bigint REFERENCES users(id) ON DELETE SET NULL,
    changed_date timestamptz
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number varchar(50) NOT NULL UNIQUE,
    supplier_id bigint NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT,
    order_date timestamptz DEFAULT now(),
    expected_delivery date,
    actual_delivery date,
    status varchar(20),
    total_amount numeric(12,2),
    notes varchar(500),
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    approved_by bigint REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS purchase_order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id bigint NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    inventory_id bigint NOT NULL REFERENCES inventory(id) ON DELETE RESTRICT,
    quantity numeric(12,2) NOT NULL,
    unit_cost numeric(12,2) NOT NULL,
    total_cost numeric(12,2) NOT NULL,
    quantity_received numeric(12,2)
);

CREATE TABLE IF NOT EXISTS transaction_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id bigint,
    old_value text,
    new_value text,
    change_type varchar(20),
    changed_by bigint REFERENCES users(id) ON DELETE SET NULL,
    change_date timestamptz
);
-- The BACPAC contains historical transaction IDs absent from InventoryTransactions.
ALTER TABLE transaction_audit DROP CONSTRAINT IF EXISTS transaction_audit_transaction_id_fkey;

COMMIT;
