import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api, dateTime, downloadCsv, money } from '../api.js';
import { Badge, Empty, Icon, imagePath, Modal, Notice, PageHeader, Shell, Stat } from '../components.jsx';
import '../original/inventory.css';
import '../original/menu.css';
import '../original/tickets.css';
import '../original/history.css';

const blankMenu = { foodName: '', foodType: 'Silog', description: '', price: '', imagePath: '', status: 'active' };
const blankInventory = { itemCode: '', itemName: '', description: '', categoryId: null, currentStock: 0, minimumStock: 0, unitCost: 0, unitPrice: 0, unitOfMeasure: 'pcs', isAvailable: true };
export const adminTabs = [{ id: 'inventory', label: 'Inventory', icon: 'box' }, { id: 'menu', label: 'Menu', icon: 'utensils', divider: true }, { id: 'tickets', label: 'Ticketing', icon: 'ticket', divider: true }, { id: 'history', label: 'Order History', icon: 'clock-rotate-left' }];

export function AdminPage() {
  const [params, setParams] = useSearchParams();
  const tab = adminTabs.some(item => item.id === params.get('page')) ? params.get('page') : 'inventory';
  return <Shell tabs={adminTabs} active={tab} onTab={page => setParams({ page })}><Operations tab={tab} /></Shell>;
}

export function Operations({ tab }) {
  const [orders, setOrders] = useState([]), [menu, setMenu] = useState([]), [inventory, setInventory] = useState([]), [categories, setCategories] = useState([]), [riders, setRiders] = useState([]);
  const [search, setSearch] = useState(''), [category, setCategory] = useState('all'), [status, setStatus] = useState('all'), [sort, setSort] = useState('newest');
  const [orderType, setOrderType] = useState('all'), [priority, setPriority] = useState('all'), [dateFilter, setDateFilter] = useState('all');
  const [dialog, setDialog] = useState(null), [form, setForm] = useState({}), [editing, setEditing] = useState(null), [details, setDetails] = useState({});
  const [error, setError] = useState(''), [success, setSuccess] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  const refresh = async () => { const [o, m, i, c, r] = await Promise.all([api('/api/orders'), api('/api/staff/menu'), api('/api/staff/inventory'), api('/api/staff/inventory-categories'), api('/api/manage/riders')]); setOrders(o.items); setMenu(m.items); setInventory(i.items); setCategories(c.items); setRiders(r.items); };
  useEffect(() => { let live = true; refresh().catch(e => { if (live) setError(e.message); }).finally(() => { if (live) setLoading(false); }); return () => { live = false; }; }, []);
  useEffect(() => { setSearch(''); setCategory('all'); setStatus('all'); setDialog(null); setError(''); setSuccess(''); }, [tab]);
  const action = async (work, message) => { setBusy(true); setError(''); setSuccess(''); try { await work(); await refresh(); setSuccess(message); return true; } catch (e) { setError(e.message); return false; } finally { setBusy(false); } };
  const close = () => setDialog(null);
  const editMenu = item => { setEditing(item?.id || null); setForm(item ? { foodName: item.food_name, foodType: item.food_type, description: item.description || '', price: item.price, imagePath: item.image_path || '', status: item.status === 'active' ? 'active' : 'inactive' } : blankMenu); setDialog('menu'); setError(''); };
  const editInventory = item => { setEditing(item?.id || null); setForm(item ? { itemCode: item.item_code, itemName: item.item_name, description: item.description || '', categoryId: item.category_id, currentStock: item.current_stock, minimumStock: item.minimum_stock, unitCost: item.unit_cost, unitPrice: item.unit_price, unitOfMeasure: item.unit_of_measure, isAvailable: item.is_available } : blankInventory); setDialog('inventory'); setError(''); };
  const save = async event => { event.preventDefault(); if (await action(() => api(`/api/staff/${dialog}${editing ? `/${editing}` : ''}`, { method: editing ? 'PATCH' : 'POST', body: form }), 'Changes saved.')) close(); };
  const changeStatus = (id, value) => action(() => api(`/api/orders/${id}/status`, { method: 'PATCH', body: { status: value } }), 'Ticket updated.');
  const viewTicket = async order => { setDialog({ type: 'ticket', order }); if (!details[order.id]) { try { const result = await api(`/api/orders/${order.id}/items`); setDetails(old => ({ ...old, [order.id]: result.items })); } catch (e) { setError(e.message); } } };
  const stockStatus = item => Number(item.current_stock) === 0 ? 'Out of Stock' : Number(item.current_stock) <= Number(item.minimum_stock) ? 'Low Stock' : 'In Stock';
  const low = inventory.filter(item => Number(item.current_stock) <= Number(item.minimum_stock));
  const filteredInventory = inventory.filter(item => `${item.item_name} ${item.description || ''}`.toLowerCase().includes(search.toLowerCase()) && (category === 'all' || String(item.category_id) === category) && (status === 'all' || stockStatus(item) === status));
  const foodCategories = [...new Set(menu.map(item => item.food_type))];
  const filteredMenu = menu.filter(item => `${item.food_name} ${item.description || ''}`.toLowerCase().includes(search.toLowerCase()) && (category === 'all' || item.food_type === category) && (status === 'all' || (status === 'active' ? item.status === 'active' : item.status !== 'active'))).sort((a, b) => sort === 'name' ? a.food_name.localeCompare(b.food_name) : sort === 'price-low' ? Number(a.price) - Number(b.price) : sort === 'price-high' ? Number(b.price) - Number(a.price) : Number(b.id) - Number(a.id));
  const inDateRange = order => {
    if (dateFilter === 'all') return true;
    const start = new Date(); start.setHours(0, 0, 0, 0);
    if (dateFilter === 'week') start.setDate(start.getDate() - (start.getDay() + 6) % 7);
    if (dateFilter === 'month') start.setDate(1);
    if (dateFilter === 'year') start.setMonth(0, 1);
    return new Date(order.created_at) >= start;
  };
  const filteredOrders = orders.filter(order => (status === 'all' || order.status === status) && `${order.ticket_number} ${order.customer_name || ''}`.toLowerCase().includes(search.toLowerCase()) && (tab !== 'history' || ((orderType === 'all' || order.order_type.replace(/[- ]/g, '').toLowerCase() === orderType.replace(/[- ]/g, '').toLowerCase()) && (priority === 'all' || order.priority === priority) && inDateRange(order))));
  const field = (key, label, props = {}) => <label>{label}<input value={form[key] ?? ''} onChange={e => setForm({ ...form, [key]: e.target.value })} {...props} /></label>;
  const scope = tab === 'inventory' ? 'inventory' : tab === 'menu' ? 'menu' : tab === 'history' ? 'history' : 'tickets';
  return <div className={`original-${scope}`}><div id="full-page-wrapper" className={tab === 'tickets' ? 'ticketing-container' : tab === 'history' ? 'order-history-container' : ''}>
    {tab === 'inventory' ? <>
      <PageHeader title="Inventory Management" subtitle="Manage ingredient stock"><button className="btn btn--secondary" onClick={() => editInventory(null)}><Icon name="plus" /> Add New Ingredient</button><button className="btn btn--primary" onClick={() => { setForm({}); setDialog('restock'); }}><Icon name="boxes-stacked" /> Bulk Restock</button></PageHeader>
      <Notice error={error} success={success} /><div className="stats-grid"><Stat label="Total Ingredients" value={inventory.length} note="All categories" icon="apple-whole" /><Stat label="Low Stock Alerts" value={low.length} note="Needs restocking" icon="triangle-exclamation" tone="low" /><Stat label="Out of Stock" value={inventory.filter(item => Number(item.current_stock) === 0).length} note="Currently unavailable" icon="circle-xmark" tone="out" /><Stat label="Inventory Value" value={money(inventory.reduce((sum, item) => sum + Number(item.current_stock) * Number(item.unit_price), 0))} note="Total stock value" icon="peso-sign" tone="value" /></div>
      <div className="filter-container"><div className="search-wrapper"><Icon name="magnifying-glass" /><input aria-label="Search ingredients" placeholder="Search by ingredient name or description..." value={search} onChange={e => setSearch(e.target.value)} /></div><select className="filter-dropdown" aria-label="Category filter" value={category} onChange={e => setCategory(e.target.value)}><option value="all">All Categories</option>{categories.map(item => <option key={item.id} value={item.id}>{item.category_name}</option>)}</select><select className="filter-dropdown" aria-label="Stock status" value={status} onChange={e => setStatus(e.target.value)}><option value="all">All Stock Status</option>{['In Stock', 'Low Stock', 'Out of Stock'].map(value => <option key={value}>{value}</option>)}</select></div>
      <div className="table-wrapper"><div className="table-inner-wrapper"><table className="full-table"><thead><tr>{['Ingredient Name', 'Category', 'Stock Status', 'Quantity', 'Unit Price', 'Total Price', 'Available', 'Actions'].map(label => <th key={label}>{label}</th>)}</tr></thead><tbody>{filteredInventory.map(item => <tr key={item.id}><td><span className="item-name">{item.item_name}</span><span className="item-category">{item.description}</span></td><td><span className="item-category">{item.category_name}</span></td><td><Badge value={stockStatus(item)} /></td><td><span className="quantity-value">{item.current_stock} {item.unit_of_measure}</span></td><td><span className="unit-price">{money(item.unit_price)}</span></td><td><span className="total-price">{money(Number(item.current_stock) * Number(item.unit_price))}</span></td><td><label className="switch"><input type="checkbox" aria-label={`${item.item_name} availability`} checked={item.is_available} disabled={busy} onChange={() => action(() => api(`/api/staff/inventory/${item.id}`, { method: 'PATCH', body: { isAvailable: !item.is_available } }), 'Availability updated.')} /><span className="slider" /></label></td><td><div className="action-icons"><button className="action-icon edit" aria-label={`Edit ${item.item_name}`} onClick={() => editInventory(item)}><Icon name="pen-to-square" /></button></div></td></tr>)}</tbody></table>{!filteredInventory.length && !loading && <Empty title="No ingredients found" />}</div></div>
    </> : tab === 'menu' ? <>
      <PageHeader title="Menu Management" subtitle="Organize and manage your food menu items"><button className="btn btn--secondary" onClick={() => editMenu(null)}><Icon name="plus" /> Add Menu</button></PageHeader><Notice error={error} success={success} />
      <div className="stats-grid"><Stat label="Total Items" value={menu.length} note="All menu items" icon="utensils" tone="total" /><Stat label="Active Items" value={menu.filter(item => item.status === 'active').length} note="Visible to customers" icon="eye" tone="active" /><Stat label="Hidden Items" value={menu.filter(item => item.status !== 'active').length} note="Not visible to customers" icon="eye-slash" tone="hidden" /><Stat label="Categories" value={foodCategories.length} note="Food categories" icon="tags" /></div>
      <div className="category-tabs">{['all', ...foodCategories].map(value => <button className={`category-tab ${category === value ? 'active' : ''}`} key={value} onClick={() => setCategory(value)}><Icon name={value === 'all' ? 'table-cells-large' : 'utensils'} /> {value === 'all' ? 'All Categories' : value}</button>)}</div>
      <div className="filter-container"><div className="search-wrapper"><Icon name="magnifying-glass" /><input placeholder="Search by food name or description..." aria-label="Search menu" value={search} onChange={e => setSearch(e.target.value)} /></div><select className="filter-dropdown" aria-label="Menu status" value={status} onChange={e => setStatus(e.target.value)}><option value="all">All Status</option><option value="active">Active</option><option value="hidden">Hidden</option></select><select className="filter-dropdown" aria-label="Sort menu" value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Sort by: Newest</option><option value="name">Sort by: Name (A–Z)</option><option value="price-high">Sort by: Price (High–Low)</option><option value="price-low">Sort by: Price (Low–High)</option></select></div>
      <div className="menus-grid">{foodCategories.filter(value => filteredMenu.some(item => item.food_type === value)).map(value => <section className="category-section" key={value}><div className="category-section-header"><div className="category-section-icon"><Icon name="utensils" /></div><h2 className="category-section-title">{value}</h2><span className="category-section-count">{filteredMenu.filter(item => item.food_type === value).length} items</span></div><div className="category-section-grid">{filteredMenu.filter(item => item.food_type === value).map(item => <article className="menu-card" key={item.id}><div className="menu-header" style={{ backgroundImage: `url("${imagePath(item.image_path)}")`, backgroundSize: 'cover', backgroundPosition: 'center', position: 'relative' }}><div className="migration-menu-cover"><Icon name="utensils" className="fa-solid fa-utensils menu-icon" /><h3 className="menu-title">{item.food_name}</h3></div></div><div className="menu-body"><div className="menu-meta"><span className="menu-code">MENU-{item.id}</span><button className="status-toggle-btn" disabled={busy} style={{ background: item.status === 'active' ? 'var(--success-green)' : 'var(--warning-orange)' }} onClick={() => action(() => api(`/api/staff/menu/${item.id}`, { method: 'PATCH', body: { status: item.status === 'active' ? 'inactive' : 'active' } }), 'Menu visibility updated.')}>{item.status === 'active' ? 'ACTIVE' : 'HIDDEN'}</button></div><p className="menu-description">{item.description || item.food_type}</p><div className="menu-footer"><div className="item-count"><Icon name="tag" /><span>{money(item.price)}</span></div><div className="menu-actions"><button className="action-icon view" aria-label={`View ${item.food_name}`} onClick={() => setDialog({ type: 'meal', item })}><Icon name="eye" /></button><button className="action-icon edit" aria-label={`Edit ${item.food_name}`} onClick={() => editMenu(item)}><Icon name="pen-to-square" /></button></div></div></div></article>)}</div></section>)}</div>{!filteredMenu.length && !loading && <Empty title="No menu items found" />}
    </> : tab === 'tickets' ? <>
      <PageHeader className="page-header-main" title="Ticket Management" subtitle="Manage and track order tickets in real-time"><button className="btn-primary-custom" onClick={() => { setForm({ items: {}, deliveryAddress: '', barangayName: '', paymentMethod: '', orderType: 'Dine-In' }); setDialog('new-ticket'); }}><Icon name="circle-plus" /> Create Ticket</button></PageHeader><Notice error={error} success={success} />
      <div className="status-tabs-container">{['Open', 'In Progress', 'Completed', 'Cancelled', 'all'].map(value => <button key={value} className={`status-tab ${status === value ? 'active' : ''}`} onClick={() => setStatus(value)}>{value === 'all' ? 'All' : value}<span className="status-badge">{value === 'all' ? orders.length : orders.filter(item => item.status === value).length}</span></button>)}</div>
      <div className="tickets-grid">{filteredOrders.map(order => <article className="ticket-card" key={order.id}><div className="ticket-icon-bg"><Icon name="receipt" /></div><div className="ticket-header"><div className="ticket-title"><Icon name="ticket" /> {order.ticket_number}</div><div className="order-number">Order #: {order.order_number}</div><div className="ticket-time"><Icon name="clock" /> {dateTime(order.created_at)}</div></div><div className="ticket-body"><div className="ticket-info"><span className="order-type"><Icon name={order.order_type === 'Delivery' ? 'motorcycle' : 'utensils'} /> {order.order_type}</span><Badge value={order.status} /></div>{order.delivery_address && <p className="delivery-address-tag"><Icon name="location-dot" /> {order.delivery_address}</p>}<div className={`rider-info-strip ${order.rider_id ? 'assigned' : 'unassigned'}`}><Icon name="motorcycle" /> {order.rider_name || 'No rider assigned yet'}</div><div className="ticket-items"><button className="migration-button" onClick={() => viewTicket(order)}><Icon name="utensils" /> View {order.item_count} order items</button></div><div className="ticket-footer"><div><Icon name="coins" /> Total: {money(order.total_amount)}</div><div className="ticket-actions">{order.status === 'Open' && <><button className="action-btn btn-start" disabled={busy} onClick={() => changeStatus(order.id, 'In Progress')}><Icon name="play" /> Start</button><button className="action-btn btn-cancel-ticket" disabled={busy} onClick={() => setDialog({ type: 'cancel', order })}>Cancel</button></>}{order.status === 'In Progress' && <><button className="action-btn btn-rider" onClick={() => { setEditing(order.id); setForm({ riderId: order.rider_id || '' }); setDialog('assign'); }}><Icon name="motorcycle" /> Assign Rider</button><button className="action-btn btn-done" disabled={busy} onClick={() => changeStatus(order.id, 'Completed')}><Icon name="check-double" /> Complete</button></>}</div></div></div></article>)}</div>{!filteredOrders.length && !loading && <Empty title="No tickets found" detail="Orders will appear here when customers check out." />}
    </> : <>
      <PageHeader className="page-header-main" headingTag="h1" title="Order History" subtitle="View and manage all customer orders"><button className="admin-btn" onClick={() => downloadCsv('TasteNet-order-history.csv', [['Ticket', 'Customer', 'Type', 'Total', 'Status', 'Date'], ...filteredOrders.map(order => [order.ticket_number, order.customer_name, order.order_type, order.total_amount, order.status, order.created_at])])}><Icon name="download" /> Export Report</button><button className="admin-btn reset-btn" onClick={() => { setSearch(''); setStatus('all'); setOrderType('all'); setPriority('all'); setDateFilter('all'); }}><Icon name="rotate-left" /> Reset Filters</button></PageHeader><Notice error={error} success={success} /><div className="stat-grid"><Stat label="Total Orders" value={orders.length} note="All customer orders" icon="shopping-bag" tone="total" /><Stat label="Completed" value={orders.filter(order => order.status === 'Completed').length} note="Successfully delivered" icon="circle-check" tone="completed" /><Stat label="In Progress" value={orders.filter(order => order.status === 'In Progress').length} note="Currently processing" icon="spinner" tone="progress" /><Stat label="Total Revenue" value={money(orders.filter(order => order.status === 'Completed').reduce((sum, order) => sum + Number(order.total_amount), 0))} note="From completed orders" icon="peso-sign" tone="revenue" /></div><div className="filter-section"><div className="filter-row"><div className="search-box"><div className="search-box__icon"><Icon name="magnifying-glass" /></div><input className="search-box__input" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by order # or customer..." aria-label="Search order history" /></div><select className="filter-dropdown" value={status} onChange={e => setStatus(e.target.value)} aria-label="History status"><option value="all">All Status</option>{['Open', 'In Progress', 'Completed', 'Cancelled'].map(value => <option key={value}>{value}</option>)}</select><select className="filter-dropdown" value={orderType} onChange={e => setOrderType(e.target.value)} aria-label="Order type"><option value="all">All Types</option><option>Delivery</option><option>Dine-In</option><option>Take-Out</option></select><select className="filter-dropdown" value={priority} onChange={e => setPriority(e.target.value)} aria-label="Order priority"><option value="all">All Priority</option><option>Normal</option><option>Rush</option></select><select className="filter-dropdown" value={dateFilter} onChange={e => setDateFilter(e.target.value)} aria-label="Order date"><option value="all">All Time</option><option value="today">Today</option><option value="week">This Week</option><option value="month">This Month</option><option value="year">This Year</option></select></div></div><div className="orders-container"><OrdersTable orders={filteredOrders} onView={viewTicket} tableClass="orders-table" /></div>
    </>}{loading && <p className="migration-loading">Loading data…</p>}
    </div>
    {['menu', 'inventory'].includes(dialog) && <Modal title={`${editing ? 'Edit' : 'Add'} ${dialog === 'menu' ? 'Food Item' : 'Ingredient'}`} onClose={close}><form className="migration-form" onSubmit={save}><Notice error={error} />{dialog === 'menu' ? <>{field('foodName', 'Food Name', { required: true })}<label>Food Type<select value={form.foodType} onChange={e => setForm({ ...form, foodType: e.target.value })}>{[...new Set([...foodCategories, 'Silog', 'Sizzling Specials', 'Special Meals', 'Beverage', 'Addons'])].map(value => <option key={value}>{value}</option>)}</select></label><label>Description<textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></label>{field('price', 'Price (₱)', { type: 'number', min: 0, step: '0.01', required: true })}{field('imagePath', 'Image path', { placeholder: 'Images/Menus/filename.jpg' })}<label>Status<select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })}><option value="active">Active</option><option value="inactive">Hidden</option></select></label></> : <><div className="migration-form-row">{field('itemCode', 'Item Code', { required: true })}{field('itemName', 'Ingredient Name', { required: true })}</div><label>Category<select value={form.categoryId || ''} onChange={e => setForm({ ...form, categoryId: e.target.value ? Number(e.target.value) : null })}><option value="">Uncategorized</option>{categories.map(item => <option key={item.id} value={item.id}>{item.category_name}</option>)}</select></label><div className="migration-form-row">{field('currentStock', 'Quantity', { type: 'number', min: 0, step: '.001', required: true })}{field('minimumStock', 'Minimum Stock', { type: 'number', min: 0, step: '.001', required: true })}{field('unitCost', 'Unit Cost (₱)', { type: 'number', min: 0, step: '.01', required: true })}{field('unitPrice', 'Unit Price (₱)', { type: 'number', min: 0, step: '.01', required: true })}</div>{field('unitOfMeasure', 'Unit of Measure', { required: true })}{field('description', 'Description')}</>}<div className="migration-form-actions"><button className="migration-button" type="button" onClick={close}>Cancel</button><button className="migration-button primary" disabled={busy}>{busy ? 'Saving…' : 'Save Changes'}</button></div></form></Modal>}
    {dialog === 'restock' && <Modal title="Bulk Restock" onClose={close}><form className="migration-form" onSubmit={async e => { e.preventDefault(); const items = Object.entries(form).filter(([, quantity]) => Number(quantity) > 0).map(([id, quantity]) => ({ id: Number(id), quantity: Number(quantity) })); if (await action(() => api('/api/staff/restock', { method: 'POST', body: { items } }), 'Stock replenished.')) close(); }}><Notice error={error} />{inventory.map(item => <label key={item.id}>{item.item_name} — {item.current_stock} {item.unit_of_measure}<input type="number" min="0" step=".001" value={form[item.id] || ''} placeholder="Quantity to add" onChange={e => setForm({ ...form, [item.id]: e.target.value })} /></label>)}<button className="migration-button primary" disabled={busy}>Restock Ingredients</button></form></Modal>}
    {dialog === 'assign' && <Modal title="Assign Rider" onClose={close}><form className="migration-form" onSubmit={async e => { e.preventDefault(); if (await action(() => api(`/api/orders/${editing}/assign`, { method: 'PATCH', body: { riderId: Number(form.riderId) } }), 'Rider assigned.')) close(); }}><Notice error={error} /><label>Select Rider<select required value={form.riderId} onChange={e => setForm({ ...form, riderId: e.target.value })}><option value="">Choose a rider</option>{riders.map(rider => <option key={rider.id} value={rider.id}>{rider.full_name} — {rider.rider_status}</option>)}</select></label><button className="migration-button primary" disabled={busy}>Assign Rider</button></form></Modal>}
    {dialog?.type === 'ticket' && <Modal title={dialog.order.ticket_number} onClose={close}><Notice error={error} /><p>{dialog.order.customer_name || 'Walk-in'} · {dialog.order.order_type}</p><div className="migration-table-wrap"><table className="migration-table"><thead><tr><th>Item</th><th>Qty</th><th>Total</th></tr></thead><tbody>{details[dialog.order.id]?.map(item => <tr key={item.id}><td>{item.food_name}<small>{item.special_instructions}</small></td><td>{item.quantity}</td><td>{money(item.sub_total)}</td></tr>)}</tbody></table></div><h3>Total: {money(dialog.order.total_amount)}</h3></Modal>}
    {dialog?.type === 'cancel' && <Modal title="Cancel Ticket" onClose={close}><p>Cancel ticket {dialog.order.ticket_number}?</p><Notice error={error} /><button className="migration-button danger" disabled={busy} onClick={async () => { if (await changeStatus(dialog.order.id, 'Cancelled')) close(); }}>Confirm Cancellation</button></Modal>}
    {dialog?.type === 'meal' && <Modal title={dialog.item.food_name} onClose={close}><img className="migration-meal-image" src={imagePath(dialog.item.image_path)} alt={dialog.item.food_name} /><p>{dialog.item.description}</p><strong>{money(dialog.item.price)}</strong></Modal>}
    {dialog === 'new-ticket' && <NewTicket menu={menu.filter(item => item.status === 'active')} close={close} action={action} error={error} busy={busy} />}
  </div>;
}

function NewTicket({ menu, close, action, error, busy }) {
  const [fees, setFees] = useState([]), [methods, setMethods] = useState([]), [form, setForm] = useState({ orderType: 'Dine-In', deliveryAddress: '', barangayName: '', paymentMethod: '', items: {} });
  useEffect(() => { let live = true; Promise.all([api('/api/delivery-fees'), api('/api/payment-methods')]).then(([f, m]) => { if (!live) return; setFees(f.items); setMethods(m.items); setForm(old => ({ ...old, barangayName: f.items[0]?.barangay_name || '', paymentMethod: m.items[0]?.method_name || '' })); }).catch(() => {}); return () => { live = false; }; }, []);
  return <Modal title="Create New Ticket" onClose={close}><form className="migration-form" onSubmit={async e => { e.preventDefault(); const items = Object.entries(form.items).filter(([, quantity]) => Number(quantity) > 0).map(([menuId, quantity]) => ({ menuId: Number(menuId), quantity: Number(quantity) })); if (await action(() => api('/api/orders', { method: 'POST', body: { items, orderType: form.orderType, deliveryAddress: form.deliveryAddress, barangayName: form.barangayName, paymentMethod: form.paymentMethod } }), 'Ticket created.')) close(); }}><Notice error={error} /><label>Order Type<select value={form.orderType} onChange={e => setForm({ ...form, orderType: e.target.value })}><option>Dine-In</option><option>Take-Out</option><option>Delivery</option></select></label>{form.orderType === 'Delivery' && <><label>Delivery Address<input value={form.deliveryAddress} onChange={e => setForm({ ...form, deliveryAddress: e.target.value })} required minLength={5} /></label><label>Barangay<select value={form.barangayName} onChange={e => setForm({ ...form, barangayName: e.target.value })}>{fees.map(item => <option key={item.id}>{item.barangay_name}</option>)}</select></label></>}<label>Payment Method<select value={form.paymentMethod} onChange={e => setForm({ ...form, paymentMethod: e.target.value })} required>{methods.map(item => <option key={item.id}>{item.method_name}</option>)}</select></label>{menu.map(item => <label key={item.id}>{item.food_name} — {money(item.price)}<input type="number" min="0" max="50" value={form.items[item.id] || ''} placeholder="Quantity" onChange={e => setForm({ ...form, items: { ...form.items, [item.id]: e.target.value } })} /></label>)}<button className="migration-button primary" disabled={busy || !methods.length}>Create Ticket</button></form></Modal>;
}

export function OrdersTable({ orders, onView, tableClass = 'custom-table' }) {
  return <div className="table-container"><div className="table-wrapper"><table className={tableClass}><thead><tr>{['Ticket #', 'Customer', 'Order Type', 'Items', 'Amount', 'Priority', 'Status', 'Date & Time', ...(onView ? ['Actions'] : [])].map(value => <th key={value}>{value}</th>)}</tr></thead><tbody>{orders.map(order => <tr key={order.id}><td><strong>{order.ticket_number}</strong></td><td>{order.customer_name || 'Walk-in'}</td><td>{order.order_type}</td><td>{order.item_count}</td><td>{money(order.total_amount)}</td><td>{order.priority || 'Normal'}</td><td><Badge value={order.status} /></td><td>{dateTime(order.created_at)}</td>{onView && <td><button className="migration-button" onClick={() => onView(order)}><Icon name="eye" /> View</button></td>}</tr>)}</tbody></table>{!orders.length && <Empty title="No orders found" />}</div></div>;
}
