import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api, dateTime, money } from '../api.js';
import { useAuth } from '../auth.jsx';
import { Badge, Empty, Icon, imagePath, Modal, Notice } from '../components.jsx';
import sections from '../original/website-sections.json';
import '../original/customer.css';

function StaticSection({ name, onClick }) { return <div onClick={onClick} dangerouslySetInnerHTML={{ __html: sections[name] }} />; }

export function CustomerPage() {
  const { user, logout, refreshUser } = useAuth();
  const navigate = useNavigate();
  const [menu, setMenu] = useState([]), [fees, setFees] = useState([]), [methods, setMethods] = useState([]), [orders, setOrders] = useState([]);
  const [cart, setCart] = useState({}), [search, setSearch] = useState(''), [query, setQuery] = useState('');
  const [dialog, setDialog] = useState(null), [profileOpen, setProfileOpen] = useState(false), [mobileOpen, setMobileOpen] = useState(false);
  const [checkout, setCheckout] = useState({ deliveryAddress: '', barangayName: '', paymentMethod: '', instructions: '' });
  const [profile, setProfile] = useState(null), [passwords, setPasswords] = useState({ currentPassword: '', newPassword: '' });
  const [error, setError] = useState(''), [success, setSuccess] = useState(''), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [scrolled, setScrolled] = useState(false);
  useEffect(() => {
    let live = true;
    Promise.all([api('/api/menu'), api('/api/delivery-fees'), api('/api/payment-methods'), user ? api('/api/orders') : { items: [] }, user ? api('/api/auth/profile') : null])
      .then(([m, f, p, o, account]) => { if (!live) return;
        setMenu(m.items); setFees(f.items); setMethods(p.items); setOrders(o.items); setProfile(account?.profile || null);
        setCheckout(old => ({ ...old, deliveryAddress: account?.profile.address || '', barangayName: f.items.find(item => account?.profile.address?.includes(item.barangay_name))?.barangay_name || f.items[0]?.barangay_name || '', paymentMethod: p.items[0]?.method_name || '' }));
      }).catch(e => { if (live) setError(e.message); }).finally(() => { if (live) setLoading(false); });
    return () => { live = false; };
  }, [user?.id]);
  useEffect(() => { const update = () => setScrolled(window.scrollY > 50); update(); window.addEventListener('scroll', update, { passive: true }); return () => window.removeEventListener('scroll', update); }, []);
  const close = () => { setDialog(null); setError(''); };
  const open = name => { setProfileOpen(false); setMobileOpen(false); setError(''); setSuccess(''); setDialog(name); };
  const updateCart = (product, delta) => setCart(old => {
    const next = { ...old }, quantity = Math.min(50, Math.max(0, (next[product.id]?.quantity || 0) + delta));
    if (!quantity) delete next[product.id]; else next[product.id] = { ...product, quantity }; return next;
  });
  const lines = Object.values(cart), count = lines.reduce((sum, item) => sum + item.quantity, 0);
  const subtotal = lines.reduce((sum, item) => sum + Number(item.price) * item.quantity, 0);
  const delivery = subtotal >= 500 ? 0 : Number(fees.find(item => item.barangay_name === checkout.barangayName)?.fee || 0);
  const categories = [...new Set(menu.map(item => item.food_type))];
  const filtered = menu.filter(item => `${item.food_name} ${item.description || ''}`.toLowerCase().includes(query.toLowerCase()));
  const act = async (work, message) => { setError(''); setSuccess(''); setBusy(true); try { await work(); setSuccess(message); return true; } catch (e) { setError(e.message); return false; } finally { setBusy(false); } };
  const placeOrder = event => { event.preventDefault(); act(async () => {
    const data = await api('/api/orders', { method: 'POST', body: { deliveryAddress: checkout.deliveryAddress, barangayName: checkout.barangayName, paymentMethod: checkout.paymentMethod, items: lines.map(item => ({ menuId: item.id, quantity: item.quantity, specialInstructions: checkout.instructions })) } });
    setCart({}); setOrders((await api('/api/orders')).items); setDialog('orders'); return data;
  }, 'Your order has been placed.'); };
  const cancel = id => act(async () => { await api(`/api/orders/${id}/status`, { method: 'PATCH', body: { status: 'Cancelled' } }); setOrders((await api('/api/orders')).items); }, 'Order cancelled.');
  const saveProfile = event => { event.preventDefault(); act(async () => { const { full_name, phone, gender, address } = profile; setProfile((await api('/api/auth/profile', { method: 'PATCH', body: { fullName: full_name, phone: phone || '', gender: gender || '', address: address || '' } })).profile); await refreshUser(); }, 'Profile updated.'); };
  const changePassword = event => { event.preventDefault(); act(async () => { await api('/api/auth/password', { method: 'PATCH', body: passwords }); setPasswords({ currentPassword: '', newPassword: '' }); }, 'Password changed.'); };
  const navLinks = [['home', 'Home'], ['about', 'About Us'], ['menu', 'Menu'], ['contact', 'Contact']];
  const checkoutOpen = () => { if (!user) { navigate('/login'); return; } open('checkout'); };
  return <div className="original-customer">
    <nav className={`navbar ${scrolled ? 'scrolled' : ''}`} aria-label="Customer navigation"><a href="#home" className="logo-container"><img src="/original-assets/LOGO.png" alt="Caballeros Logo" className="logo-img" /><span className="brand-name">Caballeros</span></a>
      <ul className="nav-links">{navLinks.map(([id, label]) => <li key={id}><a href={`#${id}`} className="nav-link">{label}</a></li>)}</ul>
      <div className="nav-icons"><button type="button" className="cart-icon-wrapper" aria-label={`Shopping cart, ${count} items`} onClick={() => open('cart')}><Icon name="basket-shopping" /><span className="cart-badge">{count}</span></button>{user ? <button type="button" aria-label="My account" onClick={() => setProfileOpen(!profileOpen)}><Icon name="circle-user" /></button> : <Link to="/login" aria-label="Sign in"><Icon name="circle-user" /></Link>}<button className={`hamburger-btn ${mobileOpen ? 'open' : ''}`} aria-label="Toggle navigation" aria-expanded={mobileOpen} onClick={() => setMobileOpen(!mobileOpen)}><span className="hbar" /><span className="hbar" /><span className="hbar" /></button></div>
      <div className={`mobile-nav-drawer ${mobileOpen ? 'open' : ''}`}>{navLinks.map(([id, label]) => <a href={`#${id}`} key={id} onClick={() => setMobileOpen(false)}>{label}</a>)}</div>
    </nav>
    {profileOpen && <><button className="profile-dropdown-overlay open" aria-label="Close account menu" onClick={() => setProfileOpen(false)} /><div className="profile-dropdown open"><div className="profile-dropdown-header"><div className="profile-avatar-small"><Icon name="user" /></div><div className="profile-name">{user.fullName}</div><div className="profile-email">{user.email}</div></div><div className="profile-dropdown-menu">{[['profile', 'circle-user', 'My Profile'], ['security', 'shield-halved', 'Security'], ['orders', 'clipboard-list', 'My Orders']].map(([id, icon, label]) => <button key={id} className="profile-dropdown-item" onClick={() => open(id)}><Icon name={icon} /><span>{label}</span></button>)}<div className="profile-dropdown-divider" /><button className="profile-dropdown-item profile-dropdown-logout" onClick={logout}><Icon name="right-from-bracket" /><span>LOG OUT</span></button></div></div></>}
    <div id="home" className="hero-container section-fade-in visible"><div className="hero-content"><h1>Sizzling Good Food,<br />Delivered Hot!</h1><div className="hero-tagline">Dasmariñas' Favorite Silog &amp; Sizzling Meals</div><div className="hero-subtitle">Lutong-Bahay Delivered to your Doorstep</div><div className="hero-description">Authentic Filipino home-based meals from Dasmariñas City's finest kitchens</div><form className="search-box" onSubmit={e => { e.preventDefault(); setQuery(search); document.getElementById('menu')?.scrollIntoView({ behavior: 'smooth' }); }}><Icon name="magnifying-glass" /><input className="search-input" aria-label="Search food" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search for Tapsilog, Sisig, or your Favorite..." /><button className="btn-search">Search</button></form><div className="cta-group"><a className="btn-order" href="#menu">Order Now!</a></div></div></div>
    <StaticSection name="about" />
    <section id="menu" className="menu-display-section section-fade-in visible"><h2 className="menu-header">DISCOVER OUR MENU</h2><Notice error={dialog ? '' : error} />{loading ? <p className="migration-loading">Loading menu…</p> : !filtered.length ? <Empty title="No menu items found" /> : categories.map(category => {
      const items = filtered.filter(item => item.food_type === category); if (!items.length) return null;
      return <div className="menu-category-container" key={category}><h3 className="category-title">{category}</h3><div className="menu-grid-container">{items.map(item => <article className="menu-container" key={item.id}><img className="menu-featured-img" src={imagePath(item.image_path)} alt={item.food_name} loading="lazy" /><div className="menu-list-container"><div className="category-label">{item.food_name}</div><div className="meal-description-short">{item.description}</div><div className="item-price-small">{money(item.price)}</div><div className="menu-item-buttons"><button className="view-btn" onClick={() => open(item)}><Icon name="eye" /> VIEW</button><button className="add-to-cart-btn-text" onClick={() => { updateCart(item, 1); setSuccess(`${item.food_name} added to your order.`); }}><Icon name="cart-plus" /> ADD</button></div></div></article>)}</div></div>;
    })}</section>
    <StaticSection name="love" /><StaticSection name="steps" />
    <div className="cta-banner"><h3 className="cta-title">Hungry? Order Now!</h3><p className="cta-subtitle">Free delivery on orders over ₱500. Delivery fee varies by barangay.</p><a href="#menu" className="btn-cta-large">Order Now</a><div className="cta-phone"><Icon name="phone" /> 046-473-9753 / 0912-368-7369</div></div>
    <StaticSection name="contact" /><StaticSection name="footer" onClick={event => { const target = event.target.closest('a'); if (target?.id === 'termsFooterLink' || target?.id === 'privacyFooterLink') { event.preventDefault(); open(target.id === 'termsFooterLink' ? 'terms' : 'privacy'); } }} />
    {success && !dialog && <div className="migration-toast" role="status"><Icon name="cart-plus" /><span>{success}</span><button aria-label="Dismiss message" onClick={() => setSuccess('')}>×</button></div>}
    {dialog === 'cart' && <div className="cart-modal" style={{ display: 'block' }}><button className="cart-modal-overlay" aria-label="Close cart" onClick={close} /><section className="cart-modal-content" role="dialog" aria-modal="true" aria-label="Your order"><div className="cart-modal-header"><h3><Icon name="basket-shopping" /> Your Order</h3><button className="cart-close-btn" aria-label="Close cart" onClick={close}>×</button></div><div className="cart-modal-body">{!lines.length ? <div className="cart-empty-state"><Icon name="basket-shopping" /><p>Your cart is empty</p><a href="#menu" className="btn-browse-menu" onClick={close}>Browse Menu</a></div> : lines.map(item => <div className="cart-item" key={item.id}><div className="cart-item-header"><div className="cart-item-name">{item.food_name}</div><div className="cart-item-price">{money(Number(item.price) * item.quantity)}</div></div><div className="cart-item-controls"><div className="quantity-controls"><button className="quantity-btn" aria-label={`Remove one ${item.food_name}`} onClick={() => updateCart(item, -1)}>−</button><span className="quantity-value">{item.quantity}</span><button className="quantity-btn" aria-label={`Add one ${item.food_name}`} onClick={() => updateCart(item, 1)}>+</button></div><button className="remove-item-btn" onClick={() => updateCart(item, -item.quantity)}><Icon name="trash" /> Remove</button></div></div>)}</div><div className="cart-modal-footer"><div className="cart-summary"><div className="cart-summary-row"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="cart-summary-row"><span>Delivery Fee</span><span>{money(delivery)}</span></div><div className="cart-summary-row cart-total"><span>Total</span><span>{money(subtotal + delivery)}</span></div></div><div className="cart-actions"><button className="btn-clear-cart" disabled={!count} onClick={() => setCart({})}>Clear Cart</button><button className="btn-checkout" disabled={!count} onClick={checkoutOpen}>Checkout</button></div><div className="cart-delivery-info"><Icon name="circle-info" /><span>Delivery fee is based on your barangay. Free delivery on orders over ₱500.</span></div></div></section></div>}
    {dialog === 'checkout' && <Modal title="Checkout" onClose={close}><form className="migration-form" onSubmit={placeOrder}><Notice error={error} /><div className="checkout-section"><h4><Icon name="location-dot" /> Delivery Address</h4><label>House, street and address<textarea required minLength={5} maxLength={1000} value={checkout.deliveryAddress} onChange={e => setCheckout({ ...checkout, deliveryAddress: e.target.value })} /></label><label>Barangay<select value={checkout.barangayName} onChange={e => setCheckout({ ...checkout, barangayName: e.target.value })} required>{fees.map(fee => <option key={fee.id}>{fee.barangay_name}</option>)}</select></label><p className="muted">Service area: Dasmariñas City only</p></div><div className="checkout-section"><h4><Icon name="credit-card" /> Payment Method</h4><div className="payment-options">{methods.map(method => <label className="payment-option" key={method.id}><input type="radio" name="paymentMethod" value={method.method_name} checked={checkout.paymentMethod === method.method_name} onChange={e => setCheckout({ ...checkout, paymentMethod: e.target.value })} required /><div className="payment-option-content"><Icon name="wallet" /><span>{method.method_name}</span>{method.instructions && <small>{method.instructions}</small>}</div></label>)}</div></div><label>Special Instructions (Optional)<textarea value={checkout.instructions} maxLength={500} onChange={e => setCheckout({ ...checkout, instructions: e.target.value })} placeholder="No chili, extra napkins, ring the bell..." /></label><div className="cart-summary-row cart-total"><span>Total</span><strong>{money(subtotal + delivery)}</strong></div><button className="migration-button primary" disabled={busy || !lines.length || !methods.length || !fees.length}>{busy ? 'Placing order…' : 'Confirm Order'}</button></form></Modal>}
    {dialog === 'orders' && <Modal title="My Orders" onClose={close} wide><Notice error={error} success={success} />{['Active Orders', 'Order History'].map((heading, index) => <div key={heading}><h3 className="migration-subheading">{heading}</h3>{orders.filter(o => index === 0 ? !['Completed', 'Cancelled'].includes(o.status) : ['Completed', 'Cancelled'].includes(o.status)).map(order => <div className="order-card" key={order.id}><div className="migration-order-row"><div><strong>Order #: {order.ticket_number}</strong><br /><small>{dateTime(order.created_at)}</small><p>Delivery to: {order.delivery_address}</p><strong>Total: {money(order.total_amount)}</strong></div><div><Badge value={order.status} />{order.status === 'Open' && <button className="btn-cancel" disabled={busy} onClick={() => cancel(order.id)}>Cancel</button>}</div></div></div>)}</div>)}{!orders.length && <Empty title="No orders yet" detail="Browse the menu to place your first order." />}</Modal>}
    {dialog === 'profile' && profile && <Modal title="My Profile" onClose={close}><form className="migration-form" onSubmit={saveProfile}><div className="profile-avatar"><Icon name="circle-user" /></div><Notice error={error} success={success} /><label>Full Name<input value={profile.full_name} required onChange={e => setProfile({ ...profile, full_name: e.target.value })} /></label><label>Email<input value={profile.email} readOnly /></label><label>Phone<input value={profile.phone || ''} onChange={e => setProfile({ ...profile, phone: e.target.value })} /></label><label>Gender<select value={profile.gender || ''} onChange={e => setProfile({ ...profile, gender: e.target.value })}><option value="">Select Gender</option><option>Male</option><option>Female</option></select></label><label>Address<textarea value={profile.address || ''} onChange={e => setProfile({ ...profile, address: e.target.value })} /></label><button className="migration-button primary" disabled={busy}>Save Changes</button></form></Modal>}
    {dialog === 'security' && <Modal title="Security — Change Password" onClose={close}><form className="migration-form" onSubmit={changePassword}><Notice error={error} success={success} /><label>Current Password<input type="password" autoComplete="current-password" required value={passwords.currentPassword} onChange={e => setPasswords({ ...passwords, currentPassword: e.target.value })} /></label><label>New Password<input type="password" autoComplete="new-password" minLength={12} required value={passwords.newPassword} onChange={e => setPasswords({ ...passwords, newPassword: e.target.value })} /></label><button className="migration-button primary" disabled={busy}>Change Password</button></form></Modal>}
    {dialog && typeof dialog === 'object' && <Modal title={dialog.food_name} onClose={close}><img className="migration-meal-image" src={imagePath(dialog.image_path)} alt={dialog.food_name} /><p>{dialog.description}</p><h3>{money(dialog.price)}</h3><button className="migration-button primary" onClick={() => { updateCart(dialog, 1); setSuccess(`${dialog.food_name} added to your order.`); close(); }}><Icon name="cart-plus" /> Add to Cart</button></Modal>}
    {['terms', 'privacy'].includes(dialog) && <Modal title={dialog === 'terms' ? 'Terms & Conditions' : 'Privacy Policy'} onClose={close}><p>{dialog === 'terms' ? 'TasteNet provides food ordering and delivery within Dasmariñas City. Prices and delivery fees are shown before confirmation. Open orders may be cancelled from My Orders. Contact Caballeros for help with an order or payment.' : 'TasteNet uses your account information and delivery address to process your orders, deliver meals, and communicate with you. Contact Caballeros for questions about your account information.'}</p></Modal>}
  </div>;
}
